enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = false
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Extended]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "TDAD68/revanced-patches"
integrations-source = "TDAD68/revanced-integrations"
cli-source = "TDAD68/revanced-cli"
rv-brand = "TED68 ReVanced"
arch = "arm64-v8a"
remove-rv-integrations-checks = true
build-mode = "both"
included-patches = "'Custom branding icon for YouTube' 'Enable slide to seek' 'Custom branding name for YouTube' 'MaterialYou'"
excluded-patches = "'GmsCore support'"
